export enum HttpMethod {
	GET = "get",
	POST = "post",
	PUT = "put",
	PATCH = "patch",
	DELETE = "delete",
}

export enum AccountType {
	USER = "USER",
	MENTOR = "MENTOR",
	STAFF = "STAFF",
}

export enum CareerYearType {
	ACADEMIC = "U",
	JOB_SEEKER = "R",
	JUNIOR = "N",
	MIDDLE = "S",
}

export const CAREER_YEAR_OPTIONS = [
	{ value: CareerYearType.ACADEMIC, label: "대학생" },
	{ value: CareerYearType.JOB_SEEKER, label: "취준생" },
	{ value: CareerYearType.JUNIOR, label: "신입~3년차" },
	{ value: CareerYearType.MIDDLE, label: "3년차 이상" },
];

export enum AskerSpecificType {
	SPECIALTY = "SPECIALTY",
	NONE_SPECIALTY = "NONE_SPECIALTY",
}

export const SPECIFIC_TYPE_OPTIONS = [
	{ value: AskerSpecificType.SPECIALTY, label: "전공자" },
	{ value: AskerSpecificType.NONE_SPECIALTY, label: "비전공자" },
];

export enum QnaAskerType {
	ALL = "ALL",
	ME = "ME",
}

export const POSITION_IDS = {
	WEB_FRONTEND: 1,
	BACKEND: 2,
	FULLSTACK: 3,
	ANDROID: 4,
	IOS: 5,
	DATA_ENGINEER: 6,
	DATA_SCIENTIST: 7,
	AI_ML: 8,
	DEVOPS: 9,
};

export const SKILL_IDS = {
	React: 6,
	"Vue.js": 7,
	Angular: 8,
	"Next.js": 9,
	Svelte: 10,
	Remix: 11,
	Vuex: 12,
	GraphQL: 13,
	Relay: 14,
	"TanStack Query(React Query)": 15,
	Redux: 16,
	Recoil: 17,
	MobX: 18,
	Emotion: 19,
	"styled-components": 20,
	Spring: 21,
	Django: 22,
	Flask: 23,
	FastAPI: 24,
	"Node.js": 25,
	Express: 26,
	NestJS: 27,
	"Spring Boot": 28,
	"Ruby on Rails": 29,
	Laravel: 30,
	".NET": 31,
	Fastify: 32,
	Android: 33,
	iOS: 34,
	"Apache Hadoop": 35,
	"Apache HBase": 36,
	"Apache Spark": 37,
	"Apache Kafka": 38,
	Tableau: 39,
	Redash: 40,
	"Power BI": 41,
	"Apache Impala": 42,
	"Jupyter Notebook": 43,
	"Apache Superset": 44,
	PyTorch: 45,
	TensorFlow: 46,
	Docker: 47,
	Kubernetes: 48,
	Terraform: 49,
	Jenkins: 50,
	Istio: 51,
	Opensearch: 52,
	Elasticsearch: 53,
	Ansible: 54,
	Python: 55,
	C: 56,
	"C++": 57,
	Java: 58,
	"C#": 59,
	JavaScript: 60,
	PHP: 61,
	Go: 62,
	Swift: 63,
	Kotlin: 64,
	Ruby: 65,
	Lua: 66,
	R: 67,
	TypeScript: 68,
	HTML5: 69,
	CSS: 70,
	Rust: 71,
	Dart: 72,
	"Objective-C": 73,
	Scala: 74,
	"React Native": 75,
	Flutter: 76,
	Redis: 77,
	Yarn: 78,
	pnpm: 79,
	webpack: 80,
	esbuild: 81,
	SWC: 82,
	Babel: 83,
	"GitHub Actions": 84,
	CircleCI: 85,
} as const;
